### ISSUE TITLE
Generate controllers.yml every request

### ISSUE THREAD

**Issue by Nowaker** [kapost/cabbage_doc#3]
I configured everything correctly but I still didn't get anything under /api/docs where I mounted CabbageDoc in my Rails application.

Only after `rake cabbagedoc:documentation` did anything start showing up there. Any chance to get everything rebuilt every request to the docs? This way we won't have to run `rake` task every second.

I noticed controllers.yml file that seems to be the source of what CabbageDoc web component renders but I can't find the location in the code that generates it or reads it.

**Comment by icebreaker** [comment]
CabbageDoc has been designed with "offline" manual generation in mind. You run `rake cabbagedoc` whenever you wanna update the documentation.

Also, it would be pretty inefficient and expensive to "generate it on the fly" for every single request.

**Comment by Nowaker** [comment]
Fully understood, I'd want this to be regenerated every request in `RAILS_ENV=development` only. I think that makes a lot of sense.

**Comment by icebreaker** [comment]
Ah, that makes sense. I'll consider adding this.

**Comment by icebreaker** [comment]
@Nowaker This is now possible (in v0.0.3) and can be "turned on" via:

``` ruby
CabbageDoc.configure do |config|
  config.dev = Rails.env.development?
end
```
